version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017
      - OLLAMA_URL=http://host.docker.internal:11434
    ports:
      - "8000:8000"
    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
      - CHAINLIT_AUTH_SECRET=your-secret-key
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend

volumes:
  mongodb_data: